import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ SessionProvider wrapper */}
        <Providers>
          <Navbar />

          {/* Background */}
          <div className="fixed inset-0 -z-30">
            <img
              src="/coffee-beans-video.gif"
              alt="Coffee Background"
              className="w-full h-full object-cover brightness-75"
            />
            <div className="absolute inset-0 bg-black/60" />
          </div>

          {children}
        </Providers>
      </body>
    </html>
  );
}
